python3 main.py --inputs_path '/blurred_1/' --results_path '/deblurred_1/' --kernel_name 'kernel_1'
python3 main.py --inputs_path '/blurred_2/' --results_path '/deblurred_2/' --kernel_name 'kernel_2'
python3 main.py --inputs_path '/blurred_3/' --results_path '/deblurred_3/' --kernel_name 'kernel_3'
python3 main.py --inputs_path '/blurred_4/' --results_path '/deblurred_4/' --kernel_name 'kernel_4'
python3 main.py --inputs_path '/blurred_5/' --results_path '/deblurred_5/' --kernel_name 'kernel_5'
python3 main.py --inputs_path '/blurred_6/' --results_path '/deblurred_6/' --kernel_name 'kernel_6'
